name: Java CI with Maven
on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  builds:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution : 'temurin'
        cache : maven
   
    - name: Build with Maven
      run: mvn clean test -Dmaven.test.failure.ignore=true

    - name: archive artifact
      uses: actions/upload-artifact@v4
      with:
        name: Extent_
        path: ./reports/*.html
